on:
  schedule:
     - cron: "45 15-22 * * *"
  workflow_dispatch:
  
name: calc_adp

jobs:
  adp_update_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.REPO_PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: ffscrapr, data.table, stringr, lubridate, piggyback, readr, dplyr, tidyr, tidyverse, purrr, cli
        name: Run adp update
      - run: |
          source("unified_adp.R")
        shell: Rscript {0}
